In [ ]:
#통계량 계산하기

In [1]:
import numpy as np

In [3]:
x = np.arange(10.0)

In [5]:
x.mean()

np.float64(4.5)

In [6]:
numbers=np.arange(20.0)
x= np.reshape(numbers,(4,5))
np.mean(x,0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [7]:
np.std(x)

np.float64(5.766281297335398)

In [8]:
np.var(x)

np.float64(33.25)

In [9]:
x= np.random.randn(3, 4)

In [10]:
np.corrcoef(x)

array([[1.        , 0.03428488, 0.05625602],
       [0.03428488, 1.        , 0.56747099],
       [0.05625602, 0.56747099, 1.        ]])

In [12]:
np.corrcoef(x[0],x[1])

array([[1.        , 0.03428488],
       [0.03428488, 1.        ]])

In [13]:
np.cov(x, rowvar=False)

array([[ 0.43608359,  0.40012341,  0.28088973, -0.43440328],
       [ 0.40012341,  0.74316117, -0.06271831, -0.57911976],
       [ 0.28088973, -0.06271831,  0.45400183, -0.12595744],
       [-0.43440328, -0.57911976, -0.12595744,  0.51940811]])

In [14]:
np.cov(x, rowvar=True)

array([[0.6803525 , 0.03109811, 0.03221523],
       [0.03109811, 1.20928566, 0.43324482],
       [0.03221523, 0.43324482, 0.48200387]])

In [15]:
# 다양한 확률 분포 사용하기

In [16]:
from scipy import stats
np.random.seed(0)
stats.binom(10, 0.5).rvs(10)

array([5, 6, 5, 5, 5, 6, 5, 7, 8, 5])

In [17]:
stats.norm().rvs(10)

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [18]:
stats.uniform().rvs(10)

array([0.14335329, 0.94466892, 0.52184832, 0.41466194, 0.26455561,
       0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ])

In [19]:
stats.chi2(df=2).rvs(10)

array([1.89399336, 1.91909595, 5.75583016, 2.29027792, 0.89103699,
       1.14906482, 2.3922156 , 0.12423059, 2.19782496, 2.22119487])

In [23]:
# 정규성 검정
x = stats.uniform().rvs(20)
k2, p = stats.normaltest(x)
print(p)

0.19495530172822773


In [24]:
# 카이제곱 검정하기
import scipy as sp
n = np.array([1, 2, 4, 1, 2, 10])
sp.stats.chisquare(n)

Power_divergenceResult(statistic=np.float64(17.799999999999997), pvalue=np.float64(0.003207792034605282))

In [26]:
# t 검정하기
np.random.seed(0)
x1 = stats.norm(0, 1).rvs(10)
x2 = stats.norm(1, 1).rvs(10)
np.mean(x1), np.mean(x2)

(np.float64(0.7380231707288347), np.float64(1.400646015162435))

In [27]:
stats.ttest_ind(x1, x2)

TtestResult(statistic=np.float64(-1.6868710732328158), pvalue=np.float64(0.10888146383913824), df=np.float64(18.0))

In [29]:
#쌍체 t 검정하기
before = [68, 56, 57, 54, 54, 48, 64, 68, 66, 51, 56, 61, 58, 55, 64, 70, 60, 62]
after  = [65, 57, 57, 54, 64, 67, 64, 67, 64, 56, 60, 60, 59, 54, 65, 71, 61, 63]
# 귀무 가설 : 처치 전후로 통증의 차이가 없다.
# 대립 가설 : 처치 전후의 통증 차이가 있다.
stats.ttest_rel(before, after)

TtestResult(statistic=np.float64(-1.645589439006556), pvalue=np.float64(0.11820970284545887), df=np.int64(17))

In [31]:
# 쌍체 t 검정하기 2 (광고실험)
before = [2, 3, 2, 3, 2]
after  = [9, 8, 9, 7, 6]
#귀무가설:광고 전후로 선호도 차이가 없다.
#대립가설:광고 전후의 선호도 차이가 있다.
stats.ttest_rel(before, after)

TtestResult(statistic=np.float64(-7.961865632364446), pvalue=np.float64(0.001348170975769803), df=np.int64(4))